# @AUTHOR: imyme6yo "imyme6yo@gmail.com"
# @CREATE: 20191223 

# Arguments
ARG NODE_VERSION=12.14.0
ARG ALPINE_VERSION=3.10
ARG TAG=${NODE_VERSION}-alpine${ALPINE_VERSION}

FROM node:${TAG}

# Labels
# Maintainer
LABEL maintainer="imyme6yo"
LABEL email="imyme6yo@gmail.com"
