# @AUTHOR: imyme6yo "imyme6yo@gmail.com"
# @CREATE: 20191223 

# Arguments
ARG VERSION=1.9.4
ARG TAG=${VERSION}-alpine

FROM elixir:${TAG}

# Labels
# Maintainer
LABEL maintainer="imyme6yo"
LABEL email="imyme6yo@gmail.com"
